In [1]:
#Importa a biblioteca com um alias chamado 'np'
import numpy as np

## Vetor n-dimensional Numpy
##### É criado a partir de uma lista python, transformado em um vetor numpy.
##### Array unidimensional é semelhante a uma matriz coluna.
##### Matrizes são vetores multidimensionais.

In [2]:
# Cria um vetor a partir de um array python
vetor = np.array([1, 2, 3, 4, 5, 6, 7])

type(vetor)

numpy.ndarray

In [3]:
# Cria um array numpy a partir de uma lista python previamente criada
lista = [0, 1, 2, 3, 4, 5, 6]
vetor_da_lista = np.array(lista)

type(vetor_da_lista)

numpy.ndarray

In [4]:
# Cria um array numpy automaticamente, com os argumentos: (Inicio, Fim, Intervalo)
vetor_auto = np.arange(1, 6, 1)

print(vetor_auto)
type(vetor_auto)

[1 2 3 4 5]


numpy.ndarray

In [5]:
# Função que mostra as dimensões do array numpy (linhas, colunas)
print(vetor.shape)
print(vetor_da_lista.shape)
print(vetor_auto.shape)

(7,)
(7,)
(5,)


In [6]:
# A função sum(array) soma os elementos do array.
np.sum(vetor)

28

In [7]:
# Funçoes amin e amax retornam o minimo e o maximo do array respectivamente.
print(np.amin(vetor))
print(np.amax(vetor))

1
7


In [8]:
# Funções argmin e argmax retornam o indice do minimo e maximo elementos respectivamente.
print(np.argmin(vetor))
print(np.argmax(vetor))

0
6


In [9]:
# Retorna o numero de elementos no array.
print(vetor.size)

7


In [10]:
# Retorna o número de dimensões do array.
print(vetor.ndim)

1


### Matrizes
#### Vetores multidimensionais numpy.

In [11]:
# Função que cria uma matriz vazia (dimensões, tipo).
vazia = np.empty([2,2], dtype=int)

In [12]:
# Função que cria um array com apenas elementos zeros (dimensões, tipo).
zero = np.zeros([3, 3], dtype=int)
print(zero)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [13]:
# Função que cria um array com apenas elementos um (dimensões, tipo).
ums = np.ones([3,3], dtype=int)
print(ums)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
# Função que cria uma matriz identidade (dimensão, tipo).
identidade = np.eye(3, dtype=int)
print(identidade)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [15]:
# Função que cria uma matriz diagonal com os elementos escolhidos previamente em um array.
vet = np.array([1, 2, 3])
diagonal = np.diag(vet)

print(diagonal)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [16]:
# Função que se utilizada com vetores de 1 dimensão retorna o produto interno.
# Função que se utilziada com vetores de mais de uma dimensão, realiza multiplicação de matrizes.
# Segue as propriedades da Algebra Linear sobre multiplicação de Matrizes.
x = np.array([1, 2])
y = np.array([2, 1])

z1 = np.dot(x, y)

# São semelhantes em alguns aspectos a função dot.
z2 = np.inner(x, y)
z3 = np.matmul(x, y)
print(z1)
print(z2)
print(z3)

4
4
4


In [17]:
# Função que retorna a transposta de uma matriz.
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [18]:
# Função que cria uma matriz a partir de uma lista de vetores python ou numpy.
matriz_numpy = np.matrix([[1, 2], [3, 4]])
matriz_numpy

matrix([[1, 2],
        [3, 4]])

In [19]:
# Inverso de uma  matriz.
matriz_numpy.getI()

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

#### Gerando números e arrays numpy.

In [20]:
# Função que gera um intervalo de números (Inicio, Fim, quantidade de elementos)
lin = np.linspace(2, 3, num=5)
lin

array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])

In [21]:
# Função que gera numeros aleatorios em ponto flutuante (Dimensões).
aleatorio_float = np.random.rand(2,2)
aleatorio_float

array([[ 0.70029762,  0.31012917],
       [ 0.27555232,  0.75095099]])

In [22]:
# Função que gera numeros aleatorios da distribuição normal (Dimensões).
aleatorio_normal = np.random.randn(2,2)
aleatorio_normal

array([[ 1.6306147 ,  0.30110912],
       [-2.09191011, -0.13287345]])

In [23]:
# Função que gera numeros aleatorios inteiros (Inicio incluso, Fim excluso, size = quantidade(tupla ou numero))
aleatorio_inteiro = np.random.randint(0, 10, size=5)
aleatorio_inteiro

array([8, 7, 8, 0, 6])

In [24]:
# Função que gera numeros aleatorios float num intervalo entre 0 e 1 (quantidade, pode ser tupla).
aleatorio_float_sample = np.random.random_sample((5,3))
aleatorio_float_sample                                                

array([[ 0.40377279,  0.4127262 ,  0.70332935],
       [ 0.35248163,  0.01790989,  0.95942042],
       [ 0.70421121,  0.73660573,  0.14489312],
       [ 0.12225374,  0.51271771,  0.94550249],
       [ 0.66187439,  0.36962679,  0.35603218]])